//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DispLogCurve.rc
//
#define IDR_DISPLOGCURVETYPE            400
#define IDS_PROPSHT_CAPTION             401
#define CG_IDR_POPUP_DISP_LOG_CURVE_VIEW 402
#define IDR_DISPLOGCURVE_TOOLBAR        403
#define IDR_POPUP_DISPLOGCURVE          404
#define IDI_ICONCURVE                   405
#define IDD_DLG_LANE_SET                406
#define IDD_DLG_CURVE_SET               407
#define IDD_DLG_DISPDEPTH_SET           408
#define IDD_DLG_LANE_ADD                409
#define IDD_DLG_ADD_CURVE               410
#define IDB_BS0                         411
#define IDB_BS1                         412
#define IDB_BS2                         413
#define IDB_BS3                         414
#define IDB_BS4                         415
#define IDB_BS5                         416
#define IDD_LOGTEMPLPAGE1               417
#define IDD_LOGTEMPLPAGE2               418
#define IDD_LOGTEMPLPAGE0               419
#define IDD_DLG_SETWIDTH                420
#define IDI_DEPTH                       424
#define IDI_LOG                         425
#define IDD_DLG_EDIT_TEMPL              429
#define IDD_DLG_SELECT_TEMPL            431
#define IDD_DLG_SELECT_WELL             444
#define IDD_DLG_LANE_TEMPL              448
#define IDD_DLG_LOGING_TEMPL            449
#define IDI_INTERLAYER                  453
#define IDC_GRID                        2201
#define IDC_BTN_FILLCOLOR               2202
#define IDC_CHECK_FILL                  2203
#define IDC_CHECK_BORDER                2204
#define IDC_CHECK_HORZ                  2205
#define IDC_EDIT_CHAR                   2206
#define IDC_CHECK_VERT                  2207
#define IDC_EDIT_PATH                   2208
#define IDC_BTN_LINECOLOR               2209
#define IDC_EDIT_FIRSTROW               2210
#define IDC_CBLINESTYLE                 2211
#define IDC_SPIN1                       2212
#define IDC_LINESIZE                    2213
#define IDC_EDIT_TITLEROW               2214
#define IDC_CBFILL                      2215
#define IDC_SPIN2                       2216
#define IDC_BSSTYLE                     2217
#define IDC_LIST_DATA                   2218
#define IDC_EDIT_TITLEWIDTH             2219
#define IDC_STATIC_TITLE                2220
#define IDC_BTN_APPLY                   2221
#define IDC_EDIT_DEPTH_COL              2222
#define IDC_SPIN3                       2223
#define IDC_EDIT_MIN                    2224
#define IDC_EDIT_MAX                    2225
#define IDC_BTN_WIDTH                   2226
#define IDC_EDIT_CMIN                   2227
#define IDC_EDIT_CMAX                   2228
#define IDC_FILLCOLOR                   2229
#define IDC_EDIT_STEPS                  2230
#define IDC_EDIT_MSTEPS                 2231
#define IDC_CHECK_DIR                   2232
#define IDC_CHECK_LOGCOORD              2233
#define IDC_CHECK_SAMECOORD             2234
#define IDC_EDIT_MINVAL                 2235
#define IDC_EDIT_MAXVAL                 2236
#define IDC_EDIT_MINDEPTH               2237
#define IDC_EDIT_MAXDEPTH               2238
#define IDC_EDIT_CURVE_FORMULA          2239
#define IDC_EDIT_CURVE_NAME             2240
#define IDC_LIST_LOG_NAME               2241
#define IDC_CHECK_CUSTOM_CURVER         2242
#define IDC_EDIT_WIDTH                  2243
#define IDC_MSFLEXGRID1                 2244
#define IDC_EDIT_DEPTH                  2245
#define IDC_EDIT_VAR                    2246
#define IDC_STATIC_1                    2247
#define IDC_LIST_LANE                   2248
#define IDC_CHECK_APPLY_ALL             2249
#define IDC_BTN_DEL                     2250
#define IDC_COMBO_TEMPL                 2251
#define IDC_CHECK_OILGROUP              2252
#define IDC_CHECK_OILLAYER              2253
#define IDC_CHECK_XCH                   2254
#define IDC_CHECK_OILBOTTOM             2255
#define IDC_CHECK_WATERTOP              2256
#define IDC_RADIO1                      2257
#define IDC_RADIO2                      2258
#define IDC_RADIO3                      2259
#define IDC_RADIO4                      2260
#define IDC_RADIO5                      2261
#define IDC_RADIO6                      2262
#define IDC_RADIO7                      2263
#define IDC_COMBO_WELL_NAME             2266
#define IDC_EDIT_SO                     2280
#define IDC_BTN_ALL_SELECTED            2286
#define IDC_BTN_RES_SELECTED            2287
#define IDC_BTN_ADD_LANE                2289
#define IDC_BTN_DEL_LANE                2290
#define IDC_BTN_UP                      2291
#define IDC_BTN_DOWN                    2292
#define IDC_LIST_LOGING                 2293
#define IDC_BTN_ADD_LOGING              2295
#define IDC_BTN_DEL_LOGING              2296
#define IDC_LIST_LOGINGS                2297
#define IDC_EDIT_TITLE                  2298
#define IDS_PROPSHT_CAPTION1            2364
#define ID_VIEW_CUSTOMIZE               32770
#define ID_WINDOW_MANAGER               32772
#define ID_DHELP1                       32775
#define ID_DHELP2                       32776
#define ID_DHELP3                       32777
#define ID_VIEW_FULLSCREEN              32778
#define ID_MDI_NEW_VERT_GROUP           32780
#define ID_MDI_NEW_HORZ_TAB_GROUP       32781
#define ID_MDI_MOVE_TO_PREV_GROUP       32782
#define ID_MDI_CANCEL                   32783
#define ID_MDI_MOVE_TO_NEXT_GROUP       32784
#define ID_FUNCTION_PANEL               32785
#define ID_RE_LOGIN                     32789
#define ID_DB_PW                        32790
#define ID_TOOLS_ENTRY                  32791
#define ID_WELL_MAP                     32805
#define ID_FILE_SAVE_ALL                32885
#define ID_VIEW_APPLOOK_2003            32941
#define ID_FILE_MRU_PRJ1                33172
#define ID_FILE_MRU_PRJ2                33173
#define ID_FILE_MRU_PRJ3                33174
#define ID_FILE_MRU_PRJ4                33175
#define ID_FILE_MRU_PRJ5                33176
#define ID_FILE_MRU_PRJ6                33177
#define ID_FILE_MRU_PRJ7                33178
#define ID_FILE_MRU_PRJ8                33179
#define ID_FILE_MRU_PRJ9                33180
#define ID_FILE_MRU_PRJ10               33181
#define ID_FILE_MRU_PRJ11               33182
#define ID_FILE_MRU_PRJ12               33183
#define ID_FILE_MRU_PRJ13               33184
#define ID_FILE_MRU_PRJ14               33185
#define ID_FILE_MRU_PRJ15               33186
#define ID_FILE_MRU_PRJ16               33187
#define ID_ZOOM_IN                      33200
#define ID_ZOOM_11                      33201
#define ID_ZOOM_OUT                     33202
#define ID_DEPTH_SEGMENT                33203
#define ID_VIEW_SCALE                   33204
#define ID_VIEW_LOGCURVEBAR             33205
#define ID_IMPORT_DAT                   33206
#define ID_IMPORT_DAT_DB                33207
#define ID_EXPORT_DISPLOGCURVE          33208
#define ID_VIEW_DISPCAPTION             33209
#define ID_VIEW_DISPCOMMENT             33210
#define ID_VIEW_DISPLEGEND              33211
#define ID_VIEW_LANE_PROP               33212
#define ID_INSERT_LANE                  33213
#define ID_APPEND_LANE                  33214
#define ID_ADD_CURVE                    33215
#define ID_DEL_LANE                     33216
#define ID_EDIT_COPY_INTER              33217
#define ID_EDIT_PASTE_INTER             33218
#define ID_EDIT_CUT_INTER               33219
#define ID_DISP_TEMPL                   33220
#define ID_EDIT_DISP_TEMPL              33221
#define ID_EDIT_CUT_OILBOTTOM           33222
#define ID_EDIT_COPY_OILBOTTOM          33223
#define ID_EDIT_PASTE_OILBOTTOM         33224
#define ID_EDIT_CUT_WATERTOP            33225
#define ID_EDIT_COPY_WATERTOP           33226
#define ID_EDIT_PASTE_WATERTOP          33227
#define ID_CALC_PA                      33228
#define ID_VIEW_WATCH                   33229
#define ID_DEL_CURVE                    33230
#define ID_EDIT_CUT_INTERLAYER          33231
#define ID_EDIT_COPY_INTERLAYER         33232
#define ID_EDIT_PASTE_INTERLAYER        33233

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        454
#define _APS_NEXT_COMMAND_VALUE         33234
#define _APS_NEXT_CONTROL_VALUE         2299
#define _APS_NEXT_SYMED_VALUE           2370
#endif
#endif
