//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Interlayer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_MODEL               125
#define IDS_TOOLBAR_2DVIEW              126
#define IDS_TOOLBAR_CUSTOMIZE           127
#define ID_VIEW_CUSTOMIZE               128
#define IDR_MAINFRAME                   129
#define IDR_MAINFRAME_256               130
#define ID_INDICATOR_COORD              131
#define IDR_ProjectTYPE                 132
#define ID_WINDOW_MANAGER               133
#define IDS_WINDOWS_MANAGER             134
#define ID_VIEW_FILEVIEW                135
#define ID_VIEW_CLASSVIEW               136
#define ID_VIEW_2DVIEW                  137
#define ID_PROPERTIES                   138
#define ID_OPEN                         139
#define ID_OPEN_WITH                    140
#define ID_DUMMY_COMPILE                141
#define ID_CLASS_ADD_MEMBER_FUNCTION    142
#define ID_CLASS_ADD_MEMBER_VARIABLE    143
#define ID_CLASS_DEFINITION             144
#define ID_CLASS_PROPERTIES             145
#define ID_NEW_FOLDER                   146
#define ID_SORT_MENU                    147
#define ID_SORTING_GROUPBYTYPE          148
#define ID_SORTING_SORTALPHABETIC       149
#define ID_SORTING_SORTBYTYPE           150
#define ID_SORTING_SORTBYACCESS         151
#define ID_VIEW_OUTPUTWND               152
#define ID_VIEW_PROPERTIESWND           153
#define ID_SORTPROPERTIES               154
#define ID_PROPERTIES1                  155
#define ID_PROPERTIES2                  156
#define ID_EXPAND_ALL                   157
#define IDS_FILE_VIEW                   158
#define IDS_CLASS_VIEW                  159
#define IDS_OUTPUT_WND                  160
#define IDS_PROPERTIES_WND              161
#define IDS_GRAPH_VIEW                  162
#define IDI_FILE_VIEW                   163
#define IDI_FILE_VIEW_HC                164
#define IDI_CLASS_VIEW                  165
#define IDI_MODEL_VIEW                  166
#define IDI_CLASS_VIEW_HC               167
#define IDI_MODEL_VIEW_HC               168
#define IDI_OUTPUT_WND                  169
#define IDI_OUTPUT_WND_HC               170
#define IDI_PROPERTIES_WND              171
#define IDI_PROPERTIES_WND_HC           172
#define IDR_EXPLORER                    173
#define IDI_FILE_VIEW_HC1               174
#define IDI_2D_VIEW_HC                  175
#define IDI_GRAPH_VIEW_HC               176
#define IDB_EXPLORER_24                 177
#define IDI_2D_VIEW                     178
#define IDI_GRAPH_VIEW                  179
#define IDR_SORT                        180
#define IDB_SORT_24                     181
#define IDR_POPUP_SORT                  182
#define IDR_POPUP_EXPLORER              183
#define IDB_CLASS_VIEW                  184
#define IDB_MODEL_VIEW                  185
#define IDB_CLASS_VIEW_24               186
#define IDB_MODEL_VIEW_24               187
#define IDR_MENU_IMAGES                 188
#define IDB_MENU_IMAGES_24              189
#define ID_TOOLS_MACRO                  190
#define IDR_OUTPUT_POPUP                191
#define IDR_PROPERTIES                  192
#define IDB_PROPERTIES_HC               193
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_INDICATOR_PRESS              219
#define ID_INDICATOR_CENTER             220
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_TOOLBAR_MODEL               310
#define IDR_TOOLBAR_MODEL_256           311
#define IDR_TOOLBAR_2DVIEW              313
#define IDR_TOOLBAR_2DVIEW_256          314
#define IDR_POPUP_MENU                  315
#define IDD_DLG_GRID_PROP_SETUP         316
#define IDC_CURSOR_HAND                 317
#define IDC_CURSOR_ZOOM_RECT            318
#define IDB_TREE_STATE                  319
#define IDB_TREE_STATE_32               319
#define IDB_TREE_STATE_24               320
#define IDR_POPUP_TREE                  321
#define IDB_GRAPH_VIEW_24               321
#define IDB_GRAPH_VIEW                  322
#define IDD_DLG_IMPORT_MODEL            322
#define IDD_DLG_IMPORT_WELLINFO         323
#define IDR_3DViewTYPE                  324
#define IDR_2DViewTYPE                  326
#define IDR_HTML_DISPPIC                329
#define IDR_TOOLBAR_ALIGIN              330
#define IDR_TOOLBAR_ATTRI               332
#define ID_DRAW_BASE_LINE               334
#define IDR_TOOLBAR_CURVE_BASE_OBJ      334
#define IDR_TOOLBAR_ELEMENTSORT         336
#define IDR_TOOLBAR_FORMAT              338
#define IDR_TOOLBAR_POINT               340
#define IDR_TOOLBAR_RECT_BASE_OBJ       342
#define IDR_TOOLBAR_ZOOM                346
#define IDR_TOOLBAR_DRAW                348
#define IDR_POPUP_GEOMAP                350
#define IDR_GeoMapTYPE                  351
#define IDC_CURSOR_ADD_PT               352
#define IDC_CURSOR_ATTRI_BRUSH          353
#define IDC_CURSOR_DEL_PT               354
#define IDC_CURSOR_DIVIDE_LINE          355
#define IDC_CURSOR_DIVIDE_LINE_DOWN     356
#define IDC_CURSOR_HAND_1               357
#define IDC_CURSOR_HAND_2               358
#define IDC_CURSOR_JOIN_LINE            359
#define IDC_CURSOR_PTMOVE               360
#define IDC_CURSOR_MOVE_PT              360
#define IDC_CURSOR_SIZEALL              361
#define IDC_CURSOR_ZOOM_IN              362
#define IDC_CURSOR_ZOOM_OUT             363
#define IDC_PENCIL                      364
#define IDB_ARROWS                      365
#define IDB_BITMAP_01                   397
#define IDB_BITMAP_02                   398
#define IDD_DLG_LINE_SET                398
#define IDB_BITMAP_03                   399
#define IDD_DLG_POLY_SET                399
#define IDB_BITMAP_04                   400
#define IDD_DLG_RECT_SET                400
#define IDB_BITMAP_05                   401
#define IDD_PROPPAGE1                   401
#define IDB_BITMAP_06                   402
#define IDD_PROPPAGE2                   402
#define IDB_BITMAP_07                   403
#define IDD_PROPPAGE3                   403
#define IDB_BITMAP_08                   404
#define IDD_PROPPAGE4                   404
#define IDB_BITMAP_09                   405
#define IDB_BITMAP_10                   406
#define IDB_BITMAP_11                   407
#define IDB_BITMAP_12                   408
#define IDB_BITMAP_13                   409
#define IDB_BITMAP_14                   410
#define IDB_BITMAP_15                   411
#define IDB_BITMAP_16                   412
#define IDB_BITMAP_17                   413
#define IDB_BITMAP_18                   414
#define IDB_BITMAP_19                   415
#define IDD_FORM_WELLINFO               416
#define IDB_BITMAP_20                   416
#define IDD_FORM_WELLPATH               417
#define IDB_BITMAP_21                   417
#define IDD_FORM_WELLPATH_INFO          418
#define IDB_BITMAP_22                   418
#define IDB_BITMAP_23                   419
#define IDB_BITMAP_24                   420
#define IDB_BITMAP_25                   421
#define IDB_BITMAP_26                   422
#define IDB_BITMAP_27                   423
#define IDB_BITMAP_28                   424
#define IDB_BITMAP_29                   425
#define IDB_BITMAP_30                   426
#define IDB_BITMAP_31                   427
#define IDB_BITMAP_32                   428
#define IDB_BITMAP_33                   429
#define IDB_BITMAP_34                   430
#define IDB_BITMAP_35                   431
#define IDB_BITMAP_36                   432
#define IDB_BITMAP_37                   433
#define IDB_BITMAP_38                   434
#define IDB_BITMAP_39                   435
#define IDB_BITMAP_40                   436
#define IDB_BITMAP_41                   437
#define IDB_BITMAP_42                   438
#define IDB_BITMAP_43                   439
#define IDB_BITMAP_44                   440
#define IDB_BITMAP_45                   441
#define IDB_BITMAP_46                   442
#define IDB_BITMAP_47                   443
#define IDB_BITMAP_48                   444
#define IDB_LAYER_IMAGES                445
#define IDR_GeoMapTYPE_CNTR_IP          446
#define IDD_DLG_EXPORT_PICTURE          447
#define IDR_TOOLBAR_LAYER               448
#define IDD_DLG_SCALERULER_SET          450
#define IDB_BMP_SCALE_1                 451
#define IDB_BMP_SCALE_2                 452
#define IDI_LAYERBAR_HC                 452
#define IDB_BMP_SCALE_3                 453
#define IDI_LAYERBAR                    453
#define IDB_BMP_SCALE_4                 454
#define IDB_BMP_SCALE_5                 455
#define IDD_DLG_WELL_SET                455
#define IDB_BMP_SCALE_6                 456
#define IDB_BMP_SCALE_7                 457
#define IDD_DLG_EDIT_CTRL_POINT         458
#define IDR_TOOLBAR_CTRL_POINT          459
#define IDC_CURSOR_ADD_CTRL_POINT       461
#define IDC_CURSOR_DEL_CTRL_POINT       462
#define IDC_CURSOR_EDIT_CTRL_POINT      463
#define IDD_DLG_LAYER_SET               465
#define IDD_FORM_WELLLOGGING_INFO       466
#define IDC_DROP_COPY_ABOVE             467
#define IDC_DROP_COPY_ROOT              468
#define IDC_DROP_COPY_SON               469
#define IDC_DROP_MOVE_ABOVE             470
#define IDC_DROP_MOVE_ROOT              471
#define IDC_DROP_MOVE_SON               472
#define IDC_NODROP                      473
#define IDI_ICON_FOLDER                 474
#define IDI_ICON_WELL_INFO              475
#define IDC_DROP_ADD_DAT                475
#define IDI_ICON_WELL_PATH              476
#define IDR_TOOLBAR_LAYER_POINT         476
#define IDR_TOOLBAR_VERT_MODEL          476
#define IDI_ICON_WELL_LOGGING           477
#define IDI_ICON_LOGGINGS               477
#define IDI_ICON_WELL_PRO               478
#define IDD_GRAPH_AXIS_PROP_PAGE        478
#define IDI_ICON_WELL_INJ               479
#define IDD_GRAPH_CHANGE_TITLE          479
#define IDI_ICON_POINT_DAT              480
#define IDD_GRAPH_DIALOG                480
#define IDI_ICON_LINE_DAT               481
#define IDD_GRAPH_GRAPH_PROP_PAGE       481
#define IDI_ICON_POLYGON_DAT            482
#define IDD_GRAPH_GRAPHICS_PROPS        482
#define IDI_ICON_PLANE_DAT              483
#define IDD_DLG_PAGE_SET                483
#define IDI_ICON_PICTRUE_DAT            484
#define IDD_FORM_DAT                    484
#define IDD_DLG_INTERLAYER_PARA         485
#define IDD_FROM_GENERATE_LAYER         486
#define IDD_DLG_POINT_SET               487
#define IDI_ICON_NORMAL                 488
#define IDI_ICON_LAYER                  489
#define IDI_ICON_WELL_DAT               490
#define IDI_ICON_LAYER_MODEL            491
#define IDI_ICON_VERT_MODELS            492
#define IDI_ICON_VERT_MODEL             493
#define IDB_3D_OBJ_STATE                494
#define IDB_3D_OBJ_STATE_24             495
#define IDB_3D_OBJ                      496
#define IDB_3D_OBJ_24                   497
#define IDI_3D_OBJ                      498
#define IDI_ICON2                       499
#define IDI_3D_OBJ_HC                   499
#define IDR_POPUP_3DVIEW                500
#define IDD_DLG_COLOR_TABLE_SET         501
#define IDD_FILECOLORTMP_COLOR_TABLE    502
#define IDD_DLG_TRIANGular              503
#define IDD_DLG_TRIANGULAR              503
#define IDD_DLG_MATERIAL                504
#define IDI_ICON_LOGGING                505
#define IDI_ICON_LOGGING_INFO           506
#define IDD_DLG_SLICE_Z                 507
#define IDD_DLG_SLICE_XY                508
#define IDD_DIALOG1                     509
#define IDD_DLG_PHYPARARANGE            509
#define IDD_TRANGLEEXPORT               510
#define IDD_DLG_PHY_CALC                512
#define IDD_DIALOG2                     513
#define IDD_DLG_PHY_ADJ                 513
#define IDC_EDIT_MINV                   1000
#define IDC_EDIT_MAXV                   1001
#define IDC_EDIT_MINDV                  1002
#define IDC_GRAPH_TITLE                 1002
#define IDC_EDIT_MAXDV                  1003
#define IDC_EDIT_GRID                   1004
#define IDC_GRAPH_CH_TITLE              1004
#define IDC_BTN_MINC                    1005
#define IDC_GRAPH_CH_COLOR              1005
#define IDC_BTN_MAXC                    1006
#define IDC_TITLE_STRING                1006
#define IDC_COMBO_TYPE                  1007
#define IDC_RADIO_COMMA                 1008
#define IDC_RADIO_TAB                   1009
#define IDC_RADIO_SPACE                 1010
#define IDC_RADIO_OTHER                 1011
#define IDC_EDIT_CH                     1012
#define IDC_X1                          1012
#define IDC_CHECK_FIRST_LINE            1013
#define IDC_X2                          1013
#define IDC_COMBO_SHEET                 1014
#define IDC_EDIT_FILE                   1015
#define IDC_BTN_FILE                    1016
#define IDC_Y1                          1016
#define IDC_EDIT_TEXT                   1017
#define IDC_Y2                          1017
#define IDC_XTITLE                      1018
#define IDC_GEN_GRAPH_PROPS_AXIS        1018
#define IDC_GRID                        1019
#define IDC_BTN_ADD_ROW                 1020
#define IDC_XUOM                        1020
#define IDC_BTN_DEL_ROW                 1021
#define IDC_YTITLE                      1021
#define IDC_GRAPH_CHOICE                1021
#define IDC_BTN_IMPORT                  1022
#define IDC_YUOM                        1022
#define IDC_BTN_EXPORT                  1023
#define IDC_GRAPH_HIDESHOW              1023
#define IDC_STATIC_INFO                 1024
#define IDC_GRAPH_POINTMARKS            1024
#define IDC_GRID_FIELDS                 1026
#define IDC_GRAPH_MOUSECOORDS           1026
#define IDC_TXT_FILE                    1027
#define IDC_XAXIS_PRECISION             1027
#define IDC_EXCEL_FILE                  1028
#define IDC_YAXIS_PRECISION             1028
#define IDC_GRAPHS_SHOWALL              1028
#define IDC_DBF_FILE                    1029
#define IDC_MDB_FILE                    1030
#define IDC_EDIT_LINE                   1031
#define IDC_SPIN_LINE                   1032
#define IDC_BTN_LOAD                    1037
#define IDC_EDIT_X                      1038
#define IDC_EDIT_Y                      1039
#define IDC_EDIT_WELL_NAME              1040
#define IDC_CHECK_SHOW                  1042
#define IDC_CHECK_LOCK                  1043
#define IDC_CHECK_CLIP                  1044
#define IDC_NEW_GRAPH_DLG               1046
#define IDC_EDIT_MARK                   1049
#define IDC_EDIT_LAYERS                 1051
#define IDC_EDIT_NORMALS                1052
#define IDC_EDIT_VERTS                  1053
#define IDC_TOP                         1054
#define IDC_BOTTOM                      1056
#define IDC_STATIC_TOP                  1057
#define IDC_STATIC_MIDDLE               1058
#define IDC_STATIC_BOTTOM               1059
#define IDC_STATIC_TOP1                 1060
#define IDC_STATIC_MODEL                1061
#define IDC_STATIC_BOTTOM1              1062
#define IDC_EDIT_TOP                    1063
#define IDC_EDIT_MIDDLE                 1064
#define IDC_EDIT_BOTTOM                 1065
#define IDC_VERT                        1066
#define IDC_STATIC_V_MODLE              1067
#define IDC_STATIC_VERT                 1068
#define IDC_HORZ                        1070
#define IDC_BTN_IMPORT_TOP              1072
#define IDC_BTN_DEL_TOP                 1073
#define IDC_BTN_IMPORT_HORZ             1074
#define IDC_BTN_DEL_HORZ                1075
#define IDC_BTN_IMPORT_BOTTOM           1076
#define IDC_BTN_DEL_BOTTOM              1077
#define IDC_BTN_IMPORT_VERT             1078
#define IDC_BTN_DEL_VERT                1079
#define IDC_BTN_GENERATE_LAYER          1080
#define IDC_BTN_IMPORT_NORMAL           1082
#define IDC_GRADIENT                    1083
#define IDC_LIST_COLOR                  1084
#define IDC_NEWPEG_POSITION             1085
#define IDC_ADD_PEG                     1086
#define IDC_NEWPEG_COLOUR               1087
#define IDC_SELPEG_POSITION             1088
#define IDC_SELPEG_COLOUR               1089
#define IDC_DEL_PEG                     1090
#define IDC_BTN_SAVE                    1092
#define IDC_STATIC_PREVIEW              1093
#define IDC_COMBO_WELLNAME              1094
#define IDC_CHECK_RULER                 1095
#define IDC_STATIC_ANGLE                1097
#define IDC_ALUM                        1101
#define IDC_BRASS                       1102
#define IDC_BRONZE                      1103
#define IDC_PBRONZE                     1104
#define IDC_COPPER                      1105
#define IDC_PCOPPER                     1106
#define IDC_GOLD                        1107
#define IDC_PGOLD                       1108
#define IDC_SILVER                      1109
#define IDC_PSILVER                     1110
#define IDC_CHROME                      1111
#define IDC_STEEL                       1112
#define IDC_EDIT_MINY                   1112
#define IDC_EMERALD                     1113
#define IDC_JADE                        1114
#define IDC_OBSIDIAN                    1115
#define IDC_RUBY                        1116
#define IDC_PEARL                       1117
#define IDC_TURQUOISE                   1118
#define IDC_PEWTER                      1119
#define IDC_BRUBBER                     1120
#define IDC_BPLASTIC                    1121
#define IDC_BTN_CLR                     1122
#define IDC_CHECK_PLANE                 1123
#define IDC_CHECK_PREVIEW               1124
#define IDC_EDIT_Z                      1125
#define IDC_CHECK_AUTO                  1126
#define IDC_EDIT_MIN                    1127
#define IDC_EDIT_MAX                    1128
#define IDC_EDIT_MINX                   1129
#define IDC_EDIT_MAXX                   1130
#define IDC_EDIT_MAXY                   1131
#define IDC_CHECK_HEIGHT                1132
#define IDC_EDIT_X1                     1133
#define IDC_EDIT_Y1                     1134
#define IDC_EDIT_Y2                     1135
#define IDC_EDIT_X2                     1136
#define IDC_EDIT1                       1137
#define IDC_EDIT2                       1138
#define IDC_EDIT3                       1139
#define IDC_BUTTON1                     1140
#define IDC_EDIT4                       1141
#define IDC_EDIT5                       1142
#define IDC_COMBO_PHY1                  1146
#define IDC_COMBO_PHY2                  1147
#define IDC_COMBO_OPERATOR              1148
#define IDC_EDIT_PARA1                  1149
#define IDC_EDIT_PHY_NEWNAME            1150
#define IDC_EDIT_PHY2                   1151
#define IDC_COMBO_OPERATOR1             1152
#define IDC_COMBO_OPERATOR2             1153
#define IDC_RADIO3                      1155
#define IDC_RADIO4                      1156
#define IDC_GROUP1                      1157
#define IDC_GROUP2                      1158
#define IDC_COMBO1                      1159
#define IDC_EDIT_NAME                   3016
#define IDC_EDIT_SCALE                  3017
#define IDC_EDIT_HPAGE                  3020
#define IDC_EDIT_VPAGE                  3021
#define IDC_EDIT_ANGLE                  3022
#define IDC_BACKCOLOR                   3035
#define IDC_FORECOLOR                   3036
#define IDC_CHECK_POLYGON               3037
#define IDC_CHECK_FILL                  3038
#define IDC_COMBO_PENTYPE               3039
#define IDC_EDIT_PENWIDE                3040
#define IDC_SPIN_PENWIDE                3041
#define IDC_CHECK_PLINE                 3042
#define IDC_EDIT_PENWIDE2               3042
#define IDC_BUTTON_PENTYPE              3043
#define IDC_COMBO_PENSTYLE              3044
#define IDC_BUTTON_PENTYPE_2            3045
#define IDC_COMBO_LINETYPE              3045
#define IDC_BUTTON_FILLTYPE             3046
#define IDC_SLIDER_TRANS                3047
#define IDC_EDIT_PENWIDE_2              3048
#define IDC_BUTTON_LINECOLOR            3048
#define IDC_SPIN_PENWIDE_2              3049
#define IDC_SLIDER_RECT                 3049
#define IDC_CHECK_LINEFILL              3050
#define IDC_BUTTON_LINEFILLCOLOR        3051
#define IDC_BUTTON_LINECOLOR_2          3051
#define IDC_BUTTON_FILLLINE             3052
#define IDC_BUTTON_ENDARROW             3053
#define IDC_SPIN_BEGINSIZE              3054
#define IDC_SPIN_ENDSIZE                3055
#define IDC_BUTTON_BEGINARROW           3056
#define IDC_EDIT_BEGINSIZE              3057
#define IDC_EDIT_ENDSIZE                3058
#define IDC_CHECK_SQUAREPEN             3059
#define IDC_EDIT_MARGIN_WIDTH           3070
#define IDC_COMBO_PENTYPE_2             3071
#define IDC_SPIN1                       3072
#define IDC_EDIT_LINE_WIDTH             3073
#define IDC_SPIN2                       3074
#define IDC_SPIN3                       3075
#define IDC_EDIT_SPACE_WIDTH            3076
#define IDC_BTN_FONT_COLOR              3078
#define IDC_BTN_COLOR_PEN               3079
#define IDC_EDIT_FONT_SIZE              3080
#define IDC_EDIT_HEIGHT                 3081
#define IDC_EDIT_WIDTH                  3082
#define IDC_COMBO_FONT                  3083
#define IDC_RADIO_SCALE_1               3084
#define IDC_RADIO_SCALE_2               3085
#define IDC_RADIO_SCALE_3               3086
#define IDC_RADIO_SCALE_4               3087
#define IDC_RADIO_SCALE_5               3088
#define IDC_RADIO_SCALE_6               3089
#define IDC_RADIO_SCALE_7               3090
#define IDC_BTN_PEN_COLOR               3092
#define IDC_BTN_FILL_COLOR              3093
#define IDC_COMBO_SYMBOL                3095
#define IDC_EDIT_SYMBOL_SIZE            3096
#define IDC_RADIO_APPLY_TYPE            3099
#define IDC_RADIO_APPLY_STYLE           3100
#define IDC_RADIO_APPLY_ALL             3101
#define IDC_RADIO_APPLY_OTHER           3102
#define IDC_EDIT_ZZBX                   3113
#define IDC_EDIT_HZBY                   3114
#define IDC_EDIT_BXHB                   3115
#define IDC_COMBO_STYLE                 3117
#define IDC_RADIO_TYPE2                 3180
#define IDC_RADIO_TYPE3                 3181
#define IDC_RADIO_TYPE4                 3182
#define IDC_RADIO_APPLY_LAYER           3202
#define IDC_RADIO_APPLY_PAGE            3203
#define IDC_SLIDER_QUALITY              3215
#define ID_TOPVIEW                      32771
#define ID_STLOBJ_COLOR                 32772
#define ID_BOTTOMVIEW                   32773
#define ID_STLOBJ_MATERIAL              32774
#define ID_FRONTVIEW                    32775
#define ID_STLOBJ_ERASE                 32776
#define ID_AXONVIEW                     32777
#define ID_FITALL                       32778
#define ID_ZOOMWIN                      32779
#define ID_RESET                        32780
#define ID_DMODE                        32781
#define ID_HLREMOVED                    32782
#define ID_ANTIAL                       32783
#define ID_REARVIEW                     32784
#define ID_STLOBJ_DELETE                32785
#define ID_LEFTVIEW                     32786
#define ID_SCREEN_DISPLAYALL            32787
#define ID_RIGHTVIEW                    32788
#define ID_SCREEN_BACKGROUNDCOLOR       32789
#define ID_SMOOTH                       32793
#define ID_MOVE_EYE_HAND                32795
#define ID_ROTATE_EYE_HAND              32796
#define ID_ZOOM_EYE_HAND                32797
#define ID_SELECT_OBJ                   32799
#define ID_VERTICAL_STRETCH             32800
#define ID_VERTICAL_SHRINK              32801
#define ID_DISP_GRID                    32942
#define ID_DISP_FILL                    32943
#define ID_DISP_GRADFILL                32944
#define ID_DISP_VALUES                  32945
#define ID_ZOOM_AREA                    32946
#define ID_TRACK_MODE                   32947
#define ID_VIEW_SET_SCALE_TO_FIT        32948
#define ID_VIEW_RESIZE_PARENT_TO_FIT    32949
#define ID_VIEW_UPPER_LEFT              32950
#define ID_VIEW_ZOOM_IN                 32951
#define ID_VIEW_ZOOM_DEFAULT            32952
#define ID_VIEW_ZOOM_OUT                32953
#define ID_DRAW_SELECT                  32954
#define ID_EDIT_CELL                    32955
#define ID_FUNTION                      32956
#define ID_DISP_TOP                     32957
#define ID_DISP_BOTTOM                  32958
#define ID_UP_LAYER                     32963
#define ID_DOWN_LAYER                   32964
#define ID_EXPORT_GRAPH                 32965
#define ID_EXPORT_DAT                   32966
#define ID_PROP_SETUP                   32967
#define ID_FILE_SAVE_PRJ                32968
#define ID_FILE_SAVE_AS_PRJ             32969
#define ID_FILE_CLOSE_PRJ               32970
#define ID_FILE_NEW_PRJ                 32971
#define ID_FILE_OPEN_PRJ                32973
#define IDC_EXPAND_ALL_TREE             32974
#define ID_COLLAPSE_ALL_ENTIRE_TREE     32975
#define ID_Menu                         32976
#define ID_EDIT                         32977
#define ID_EDIT_RENAME                  32978
#define ID_ADD_CHILD                    32979
#define ID_ADD_NEW_FILE                 32980
#define ID_IMPORT_MODEL                 32984
#define ID_IMPORT_MATEX                 32985
#define ID_IMPORT_FIELD                 32986
#define ID_NEW_WELL_DAT                 32987
#define ID_SEARCH_MODEL                 32988
#define ID_EXPORT_MODEL                 32990
#define ID_IMPORT_POINT                 32993
#define ID_IMPORT_LINE                  32994
#define ID_IMPORT_POLYGON               32995
#define ID_IMPORT_PLANE                 32996
#define ID_IMPORT_PICTRUE               32997
#define ID_IMPORT_                      32998
#define ID_IMPORT_TRACK                 32999
#define ID_ARRANGE_LEFT                 33001
#define ID_ARRANGE_RIGHT                33002
#define ID_ARRANGE_TOP                  33003
#define ID_ARRANGE_BOTTOM               33004
#define ID_ARRANGE_CENTER               33005
#define ID_ARRANGE_VCENTER              33006
#define ID_EVENLY_HORZ                  33007
#define ID_EVENLY_VERT                  33008
#define ID_ALIGIN_WIDTH                 33009
#define ID_ALIGIN_HEIGHT                33010
#define ID_ALIGIN_SIZE                  33011
#define ID_DRAW_SHOW                    33012
#define ID_DRAW_HIDE                    33013
#define ID_DRAW_LOCK                    33014
#define ID_DRAW_NOLOCK                  33015
#define ID_DRAW_BASE_POLYLINE           33016
#define ID_DRAW_BASE_PLINE              33017
#define ID_DRAW_BASE_POLYGON            33018
#define ID_DRAW_BASE_PLINEGON           33019
#define ID_DRAW_BASE_POLYGON_FILL       33020
#define ID_DRAW_BASE_PLINEGON_FILL      33021
#define ID_DRAW_POLYGON                 33022
#define ID_DRAW_SMOOTH_FILL             33023
#define ID_OBJECT_MOVEFORWARD           33024
#define ID_OBJECT_MOVEBACK              33025
#define ID_OBJECT_MOVETOFRONT           33026
#define ID_OBJECT_MOVETOBACK            33027
#define IDC_FONTNAME                    33028
#define IDC_FONTSIZE                    33029
#define ID_CHAR_BOLD                    33030
#define ID_CHAR_ITALIC                  33031
#define ID_CHAR_UNDERLINE               33032
#define ID_CHAR_COLOR                   33033
#define ID_CHAR_WIDTH                   33034
#define ID_CHAR_NARROW                  33035
#define ID_PARA_LEFT                    33036
#define ID_PARA_CENTER                  33037
#define ID_PARA_RIGHT                   33038
#define ID_POLY_MOVE_PT                 33039
#define ID_PLOY_ADD_PT                  33040
#define ID_POLY_DEL_PT                  33041
#define ID_POLY_DIVIDE_LINE             33042
#define ID_POLY_JOIN_LINE               33043
#define ID_DRAW_BASE_RECT_EMPTY         33044
#define ID_DRAW_BASE_RECT               33045
#define ID_DRAW_RECT                    33046
#define ID_ZOOM_IN                      33049
#define ID_ZOOM_OUT                     33050
#define ID_ZOOM_IN_POINT                33051
#define ID_ZOOM_OUT_POINT               33052
#define ID_ZOOM_RECT                    33053
#define ID_ZOOM_PAGE_CENTER             33054
#define ID_ZOOM_ALL                     33055
#define ID_ZOOM_SET_PAGE_CENTER         33056
#define ID_ZOOM_PAGE_MOVE               33057
#define ID_DRAW_ENABLE_MOVE             33059
#define ID_DUMMY_RECT                   33060
#define ID_DUMMY_CURVE                  33061
#define ID_DUMMY_POINT                  33062
#define ID_DRAW_BASE_TEXT               33063
#define ID_DRAW_BASE_PICTURE            33064
#define ID_DRAW_EDIT_CLEAR              33065
#define ID_DUMMY_ELEMENTSORT            33066
#define ID_DUMMY_ATTRI                  33067
#define ID_DRAW_CAPTURE                 33068
#define ID_DRAW_EDIT_UNDO               33069
#define ID_DRAW_EDIT_REDO               33070
#define ID_DUMMY_ZOOM                   33071
#define ID_ZOOM_PREV                    33072
#define ID_ZOOM_NEXT                    33073
#define ID_ZOOM_MOVE                    33074
#define ID_DUMMY_ALIGIN                 33075
#define ID_DISP_PAGEPANEL               33076
#define ID_OBJECT_COMB                  33077
#define ID_OBJECT_UNCOMB                33078
#define ID_DRAW_EDIT_PROPERTIES         33079
#define ID_OBJECT_SORT                  33080
#define ID_OLE_VERB_POPUP               33081
#define ID_ATTRIBUTE_BRUSH              33082
#define ID_TRIANGLE_EXPORT              33083
#define ID_FILE_EXPORT                  33084
#define ID_Vertical_Model               33085
#define ID_CANCEL_EDIT                  33086
#define ID_ADD_LAYER                    33090
#define ID_DEL_LAYER                    33091
#define ID_LAYER_SHOW                   33092
#define ID_LAYER_HIDE                   33093
#define ID_LAYER_LOCK                   33094
#define ID_LAYER_UNLOCK                 33095
#define ID_LAYER_CLIP                   33096
#define ID_LAYER_NOCLIP                 33097
#define ID_LAYER_MOVETOBACK             33098
#define ID_LAYER_MOVEBACK               33099
#define ID_LAYER_MOVEFORWARD            33100
#define ID_LAYER_MOVETOFRONT            33101
#define ID_ELEMENT_SELECTALL            33102
#define ID_DRAW_CLIP                    33103
#define ID_DRAW_SCALE_RULER             33104
#define ID_VIEW_TOOL_LAYER              33105
#define ID_VIEW_3D_OBJ                  33106
#define ID_CTRL_POINT_SET               33107
#define ID_VIEW_INTERSECT_SEARCH        33108
#define ID_DELETE_CTRL_POINT            33121
#define ID_EDIT_CTRL_POINT              33122
#define ID_DUMMY_CTRL_POINT             33123
#define ID_ADJUST_PICTRUE               33124
#define ID_EXPORT_CURVE                 33126
#define ID_EXPORT_LINE                  33127
#define ID_MOVE_POINT                   33128
#define ID_ADD_POINT                    33129
#define ID_DEL_POINT                    33130
#define ID_DEL_ALL_POINT                33131
#define ID_DEL_CURVE                    33132
#define ID_GEN_INTERLAYER               33133
#define ID_GENERATE_INTERLAYER          33134
#define ID_CALE_PARAMTER                33136
#define ID_CALE_PARAMETER               33137
#define ID_INTERLAYER_SPACE_SET         33140
#define ID_Generate_Layer               33141
#define ID_DRAW_NORMAL                  33142
#define ID_DRAW_INTERLAYER              33143
#define ID_NEW_CURVE                    33145
#define ID_SINGLE_INTERLAYER            33146
#define ID_SAVE_LAYER_MODEL             33147
#define ID_SAVE_LAYERMODEL_LINE         33148
#define ID_CHANGE_DIR                   33149
#define ID_CHANGE_DIRECTION             33150
#define ID_CHANGE_                      33151
#define ID_CHANGE_GENERAL               33152
#define ID_CHANGE_INTERLAYER            33153
#define ID_CHANGE_LINE                  33154
#define ID_CHANGE_NORMAL                33155
#define ID_SHOW_LEGEND                  33156
#define ID_3DOBJ_ERASE                  33157
#define ID_3DOBJ_DELETE                 33158
#define ID_LEGEND_COLOR                 33159
#define ID_IMPORT_FILE                  33161
#define ID_SHOW_TRIANGLUER              33162
#define ID_FILE_SAVE_ALL                33163
#define ID_RULER_LINKAGE                33165
#define ID_ANGLE_LINKAGE                33166
#define ID_MATERIAL_SET                 33167
#define ID_COLOR_SET                    33168
#define ID_LENGHT_LINKAGE               33169
#define ID_ANGLE_ZIP_LINKAGE            33170
#define ID_VERTICAL_ORIGINAL            33171
#define ID_FILE_MRU_PRJ1                33172
#define ID_FILE_MRU_PRJ2                33173
#define ID_FILE_MRU_PRJ3                33174
#define ID_FILE_MRU_PRJ4                33175
#define ID_FILE_MRU_PRJ5                33176
#define ID_FILE_MRU_PRJ6                33177
#define ID_FILE_MRU_PRJ7                33178
#define ID_FILE_MRU_PRJ8                33179
#define ID_FILE_MRU_PRJ9                33180
#define ID_FILE_MRU_PRJ10               33181
#define ID_FILE_MRU_PRJ11               33182
#define ID_FILE_MRU_PRJ12               33183
#define ID_FILE_MRU_PRJ13               33184
#define ID_FILE_MRU_PRJ14               33185
#define ID_FILE_MRU_PRJ15               33186
#define ID_FILE_MRU_PRJ16               33187
#define ID_SMOOTH_GROUND                33188
#define ID_SECTION_Z                    33189
#define ID_SECTION_XY                   33190
#define ID_3D_DICE                      33191
#define ID_SLICE_Z                      33192
#define ID_SLICE_XY                     33193
#define ID_Menu33194                    33194
#define ID_NEW_3D                       33195
#define ID_SLICE_X                      33196
#define ID_SLICE_Y                      33197
#define ID_INFILL_GRID                  33198
#define ID_WIREFRAME                    33199
#define ID_FILL                         33200
#define ID_EXPORT                       33201
#define IDC_BUTTON_INTERSECTSEARCH      33202
#define ID_BUTTON33202                  33202
#define ID_PHYPARARANGESET              33204
#define ID_EDIT_ADDPRT                  33205
#define ID_EDIT_CALCPRT                 33206
#define ID_EDIT_ADJPRT                  33207
#define ID_P                            33207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        514
#define _APS_NEXT_COMMAND_VALUE         33208
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           450
#endif
#endif
